### ISSUE TITLE
https://github.com/sercastiorg/spring-httpserver-timings-java17 is not accessible

### ISSUE THREAD

**Issue by saasvantage** [sercasti/spring-httpserver-timings#12]
Could you please check the project link and access level?.  I am not able to access.

**Comment by sercasti** [comment]
I'm not sure where you got that link from, this is the correct URL
https://github.com/sercasti/spring-httpserver-timings-java17

**Comment by saasvantage** [comment]
It is linked like this

To keep original dependencies intact, I created a separate project at https://github.com/sercastiorg/spring-httpserver-timings-java17, credits to @twobiers

**Comment by saasvantage** [comment]
Also, I don't find the artifact here

https://repo.maven.apache.org/maven2/io/github/sercasti/spring-httpserver-timings-java17/0.0.8/spring-httpserver-timings-java17-0.0.8.jar

**Comment by sercasti** [comment]
Fixed!

Downloading from central: https://repo.maven.apache.org/maven2/io/github/sercasti/spring-httpserver-timings-java17/0.0.1/spring-httpserver-timings-java17-0.0.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/io/github/sercasti/spring-httpserver-timings-java17/0.0.1/spring-httpserver-timings-java17-0.0.1.pom (7.2 kB at 20 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/io/github/sercasti/spring-httpserver-timings-java17/0.0.1/spring-httpserver-timings-java17-0.0.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/io/github/sercasti/spring-httpserver-timings-java17/0.0.1/spring-httpserver-timings-java17-0.0.1.jar (17 kB at 78 kB/s)

**Comment by sercasti** [comment]
https://central.sonatype.com/artifact/io.github.sercasti/spring-httpserver-timings-java17
